### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by MSala**
Just small improvements.
Changes in 'digitSum' function should raise a performance when library is used in long loops.

### CODE REVIEW

**Comment by smh** [comment]
Thanks :)

**Comment by MSala** [comment]
Great :) I forgot to update version, so it would be nice to do this :)
Thanks too.

**Comment by smh** [comment]
Good point, I always forget to update version and push to npm! It will have to wait until tomorrow though as I don't have my laptop at hand right now.

**Comment by MSala** [comment]
Ok, no problem ;)

**Pull request merged**
